agera_5:
  dataset: sis-agrometeorological-indicators
  request:
    version: "2_0"
    data_format: grib
    download_format: zip

era_5:
  request:
    data_format: grib
    download_format: zip
  resolution: 9000
  gee_image: ECMWF/ERA5/DAILY
  variable:
    precipitation: total_precipitation

terraclimate:
  url: https://climate.northwestknowledge.net/TERRACLIMATE-DATA/
  variable:
    precipitation: ppt
    max_temperature: tmax
    min_temperature: tmin
    wind_speed: ws
    solar_radiation: srad
    soil_moisture: soil
  resolution: 4000
  gee_image: IDAHO_EPSCOR/TERRACLIMATE

imerg:
  version: "07"
  short_name:
  # short names for Final Precipitation
    monthly: GPM_3IMERGM
    daily: GPM_3IMERGDF
    half_hourly: GPM_3IMERGHH
  resolution: 5566
  gee_image: NASA/GPM_L3/IMERG_V07
  variable:
    precipitation: precipitation

chirts:
  gee_image: UCSB-CHG/CHIRTS/DAILY
  resolution: 5566