agera_5:
  dataset: sis-agrometeorological-indicators
  request:
    version: "2_0"
    data_format: grib
    download_format: zip

era_5:
  request:
    data_format: grib
    download_format: zip

terraclimate:
  url: https://climate.northwestknowledge.net/TERRACLIMATE-DATA/
  variable:
    precipitation: ppt
    max_temperature: tmax
    min_temperature: tmin
    wind_speed: ws
    solar_radiation: srad
    soil_moisture: soil

imerg:
  version: "07"
  short_name:
    # short names for Final Precipitation
    monthly: GPM_3IMERGM
    daily: GPM_3IMERGDF
    half_hourly: GPM_3IMERGHH

chirps:
  base_url: https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_daily/tifs/p05/


tamsat:
  rainfall_url: https://gws-access.jasmin.ac.uk/public/tamsat/rfe/data/v3.1/daily/
  soil_moisture_url: https://gws-access.jasmin.ac.uk/public/tamsat/soil_moisture/data/v2.3.1/daily/